### ISSUE TITLE
setgid_group variable in main.cf template

### ISSUE THREAD

**Issue by nickbroon** [robertdebock/ansible-role-postfix#13]
## Proposed feature

Make the setgid_group value in the postfix configuration a variable, with default, that can be overridden on those systems were that group does not exist.

https://github.com/robertdebock/ansible-role-postfix/blob/96d50e4eb5c461cb17387af4e01346d8b66b114a/templates/main.cf.j2#L694

## Rationale

Using this role on an opensuse system, the Postfix setgid_group is actually 'maildrop' for executables and spools. So it would useful to be able to override the value this role uses.

## Additional context

See: https://build.opensuse.org/package/view_file/openSUSE:Factory/postfix/postfix.spec?expand=1

**Comment by robertdebock** [comment]
I think the role should solve this in `vars/main.yml`. I'll work on it and push a suggestion.

**Comment by robertdebock** [comment]
I'm wondering how to test this error, so I can write a little bit of code to see if the error is indeed resolved. Can you tell me what you saw on the Suse system? Maybe an error, maybe something not starting, all details help.

**Comment by robertdebock** [comment]
The error is fixed in version 4.1.1, thanks a lot for helping. If you could come back with a way to see if setgid_group is incorrect, that would help me/the role.

**Comment by robertdebock** [comment]
Feel free to reply to the issue, even if it's closed.
