### ISSUE TITLE
postmap is used instead of postalias to rebuild alias db

### ISSUE THREAD

**Issue by stdtom** [robertdebock/ansible-role-postfix#23]
## Describe the bug

This role uses the `postmap` command in the handler to rebuild the alias database:

https://github.com/robertdebock/ansible-role-postfix/blob/4caa217ad7b826729dea7f64a8a7092a2f16177c/handlers/main.yml#L6

This command produces warnings in the output/log file (see below).
Instead of `postmap` it should be used `postalias` [man](https://www.postfix.org/postalias.1.html) be used to update the alias database.

## Output

```
Jan  5 15:58:31 CentOS-9-64-minimal postfix/postmap[5583]: warning: /etc/aliases, line 11: record is in "key: value" format; is this an alias file?
Jan  5 15:58:31 CentOS-9-64-minimal postfix/postmap[5583]: warning: /etc/aliases, line 12: record is in "key: value" format; is this an alias file?
Jan  5 15:58:31 CentOS-9-64-minimal postfix/postmap[5583]: warning: /etc/aliases, line 15: record is in "key: value" format; is this an alias file?
Jan  5 15:58:31 CentOS-9-64-minimal postfix/postmap[5583]: warning: /etc/aliases, line 16: record is in "key: value" format; is this an alias file?
...
```

## Environment

- Control node OS: MacOS
- Control node Ansible version: ansible [core 2.14.1]
- Managed node OS: centos-stream-9  (as per the output above), ubuntu-22.04, debian-11, fedora-37, rocky-9

**Comment by robertdebock** [comment]
This is fixed through MR#24. Thanks!
