### ISSUE TITLE
compatibility_level is not set in Postfix 3.0 and later

### ISSUE THREAD

**Issue by stdtom** [robertdebock/ansible-role-postfix#25]
## Describe the bug

This role does not set the [compatibility_level](https://www.postfix.org/postconf.5.html#compatibility_level) parameter which was introduced with Postfix 3.0.
Therefore, Postfix produces warnings in the log file on every restart (see below).

## Output

```
Jan  5 16:40:56 CentOS-9-64-minimal postfix[5743]: Postfix is running with backwards-compatible default settings
Jan  5 16:40:56 CentOS-9-64-minimal postfix[5743]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Jan  5 16:40:56 CentOS-9-64-minimal postfix[5743]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
```

## Environment

- Control node OS: MacOS
- Control node Ansible version: ansible [core 2.14.1]
- Managed node OS: centos-stream-9  (as per the output above), ubuntu-22.04, debian-11, fedora-37, rocky-9

**Comment by robertdebock** [comment]
Fixes with MR#26
