### ISSUE TITLE
daemon_directory for Debian

### ISSUE THREAD

**Issue by rediculum** [robertdebock/ansible-role-postfix#4]
Debian's daemon_directory is missing in vars. It's not using /usr/libexec/postfix.
Evidence on Debian 9's mail.log
```
fatal: daemon_directory = '/usr/libexec/postfix': directory not found: No such file or directory
```

Complete the list in vars/mail.yml
```
postfix_daemon_directory:
  default: /usr/libexec/postfix
  Ubuntu: /usr/lib/postfix
  openSUSE Leap: /usr/lib/postfix
  Debian: /usr/lib/postfix/sbin
```

**Comment by robertdebock** [comment]
You are correct, a fix is on it's way.

Thanks for your help.

**Comment by robertdebock** [comment]
I'll keep the issue open until you confirm or close after a couple of days. Thansk @rediculum!

**Comment by rediculum** [comment]
Hi @robertdebock the path is incomplete. The daemon binaries are in /usr/lib/postfix/sbin. Your path also conflicts with the shlib_directory (shown in log):

```
postmulti[27137]: fatal: instance /etc/postfix, shlib_directory=/usr/lib/postfix conflicts with instance /etc/postfix, daemon_directory=/usr/lib/postfix
```

**Comment by robertdebock** [comment]
Thanks @rediculum, I'll follow up later this week.
