### ISSUE TITLE
SELinux module?

### ISSUE THREAD

**Issue by wzzrd** [robertdebock/ansible-role-postfix#8]
Hey Robert,

Consciously not following the bug report template here.

I have been looking at the reason behind the custom SELinux module a bit. I cannot find a reason why this is required, I think. On neither RHEL8 nor RHEL7 I can reproduce a dac_override error.

I have built both RHEL7 and RHEL8 VMs  to test with, but neither is problematic.

Hence, I don't think the module should be there.

Would you be open to:
a) dropping the module?
b) tagging the SELinux tasks, so they are skippable?
c) making them optional, and controlled by a variable?

Not that it's really relevant, but I've been testing with Ansible 2.9 and 2.10 from a Fedora control host.

**Comment by robertdebock** [comment]
Hi, I guess that selinux module came from some other distribution. Let me disable it locally, see what fails and report back.

You are right; if this is not required for RHEL7/8, the role should skip the selinux module tasks.

Back later!

**Comment by robertdebock** [comment]
I've retested the code without the SElinux module; it works.

The code was introduced [here](https://github.com/robertdebock/ansible-role-postfix/commit/b32f9fe0d167c4c124d5e0e0d73a0d1890cbc110). I can't reproduce the issue right now though.

Thanks for the suggestion Maxim!

Latest version will have this fix; likely 4.0.2, out in a couple of minutes.
