### ISSUE TITLE
relayhost set incorrectly on RHEL 7

### ISSUE THREAD

**Issue by benformosa** [robertdebock/ansible-role-postfix#9]
## Describe the bug
The `replace` filter inserts a `u` character into the `relayhost` on RHEL 7. RHEL 8 is not affected.
I'm guessing that this is a difference in unicode character handling between Python 2 and 3.

## Playbook

I'm using a playbook which sets the `postfix_relayhost` variable:
```yaml
---
- hosts: localhost
  become: true
  vars:
    postfix_relayhost: [mail.example.com]
  roles:
    - robertdebock.postfix
```

This generic playbook demonstrates the issue:
```yaml
---
- hosts: localhost
  vars:
    unbracketed: mail.example.com
    bracketed: [mail.example.com]
  tasks:
    - name: Old method
      debug:
        msg: "[{{ unbracketed }}]"

    - name: Current method
      debug:
        msg: |-
          {{ bracketed|replace("'", "") }}
```

## Output

RHEL 7:
```
PLAY [localhost] *****************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [localhost]

TASK [Old method] ****************************************************************************************************************************
ok: [localhost] => {
    "msg": "[mail.example.com]"
}

TASK [Current method] ************************************************************************************************************************
ok: [localhost] => {
    "msg": "[umail.example.com]"
}

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

RHEL 8:
```
PLAY [localhost] *******************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
ok: [localhost]

TASK [Old method] ******************************************************************************************************************************
ok: [localhost] => {
    "msg": "[mail.example.com]"
}

TASK [Current method] **************************************************************************************************************************
ok: [localhost] => {
    "msg": "[mail.example.com]"
}

PLAY RECAP *************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

## Environment

- Control node OS: RHEL 7.9
- Control node Ansible version: 2.9.17
- Managed node OS: RHEL 7.9

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by benformosa** [comment]
I can see that this was changed in commit 9c1e8d9. I think it's a little unclear why the variable is specified as a yaml sequence/list, despite the usual use including brackets.
Postfix allows a few ways of specifying the relayhost (see [man 5 postconf](http://www.postfix.org/postconf.5.html#relayhost)), which may include brackets or several other forms.

> relayhost (default: empty)
> The next-hop destination(s) for non-local mail; overrides non-local domains in recipient addresses. This information is overruled with relay_transport, sender_dependent_default_transport_maps, default_transport, sender_dependent_relayhost_maps and with the transport(5) table.
> 
> On an intranet, specify the organizational domain name. If your internal DNS uses no MX records, specify the name of the intranet gateway host instead.
> 
> In the case of SMTP or LMTP delivery, specify one or more destinations in the form of a domain name, hostname, hostname:port, [hostname]:port, [hostaddress] or [hostaddress]:port, separated by comma or whitespace. The form [hostname] turns off MX lookups. Multiple destinations are supported in Postfix 3.5 and later.
> 
> If you're connected via UUCP, see the UUCP_README file for useful information.
> 
> Examples:
> 
> ```
> relayhost = $mydomain
> relayhost = [gateway.example.com]
> relayhost = mail1.example:587, mail2.example:587
> relayhost = [an.ip.add.ress]
> ```

I would suggest it might be better to specify `postfix_relayhost` as a string, and allow the user to set it to whatever value they want.

**Comment by robertdebock** [comment]
Hi, it's likely because "[" and "]" are characters that yaml interprets. I'll check what I can do, thanks for the report!
